//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Detetive.WEB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Detetive.WEB.JsResources", typeof(JsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if(confirm(&apos;Deseja fazer uma acusação?&apos;)) 
        ///	showAccuse( {0} );
        ///else {
        ///	var btn = document.getElementById(&apos;btnSetTimer&apos;);
        ///	btn.click();
        ///}.
        /// </summary>
        internal static string showAccuse {
            get {
                return ResourceManager.GetString("showAccuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function showCards() {
        ///    var divBackGround = &quot;&lt;div class=\&quot;backAccuse\&quot;&gt;&lt;/div&gt;&quot;;
        ///    $(&quot;body&quot;).append(divBackGround + &quot;&lt;div class=\&quot;accusePanel\&quot;&gt;&quot; + &quot;&lt;div class=\&quot;spaceHeader\&quot;&gt;&quot; +
        ///                &quot;&amp;nbsp;&quot; +
        ///            &quot;&lt;/div&gt;&quot; +
        ///            &quot;&lt;div&gt;&quot; +
        ///                &quot;&lt;div class=\&quot;spaceLeft\&quot;&gt;&quot; +
        ///                    &quot;&amp;nbsp;&quot; +
        ///                &quot;&lt;/div&gt;&quot; +
        ///                &quot;&lt;div class=\&quot;imageLocal\&quot;&gt;&quot; +
        ///                    &quot;&lt;img id=\&quot;imgLocal\&quot; src=\&quot;Images/Cards/&quot; + imageRoom  + &quot;\&quot; alt=\&quot;\&quot; widt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string showCard {
            get {
                return ResourceManager.GetString("showCard", resourceCulture);
            }
        }
    }
}
